server:
  servlet:
    context-path: /api

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hihibernate.cache.use_second_level_cache: true
      hihibernate.cache.use_query_cache: false
      hihibernate.general_statistics: true

logging:
  file:
    path: /var/log/ewig/celeb/app.log
    max-size: 50MB
  level: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} reqId-%X{requestId} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %M : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} reqId-%X{requestId} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %M : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"


app:
  auth:
    auth-token-secret: XYRCTFUGVBJH%$^%&$%*&(^*YUGJFCGHXFSW$^DYC
    auth-token-life-span: 360000 # 1 hour
    refresh-token-life-space: 1800000 3 # 5 hours

